2017wk38
nmav/ipcalc pull request #10
Opened 2017-09-24 20:33 UTC by kerolasa

Here is latest set of improvements. Each commit should have explanation why they are needed, if not that needs to be fixed before merge.

2017-09-27 19:28 UTC, nmav commented
Could you check the travis failure? As far as I understand you are eliminating compiler warnings. Wouldn't it make sense to enhance the travis CI with a -Wall and -Werror build? Possibly a static analyzer too, to prevent the introduction of such issues in the future?

2017-10-01 16:42 UTC, kerolasa commented
That travis failure does not tell too much why it happen. Let me setup my own debugging travis and sort that out (not today, but lets say within a week).

I will leave adding -Wall and -Werror to you, as they are policy decisions and I think it's maintainer who needs to choose the level of strictness.

2017-10-01 20:28 UTC, kerolasa commented
Oh my. I must be happy that there is automatic tests, the issue was correctly reported and as silly as bugs go. Call to atexit(function) always returned none-zero return value. That is now fixed to fail only when appropriate.

2017-10-12 19:57 UTC, nmav requested changes
Overall the changes are fine; few patches I don't think should be included. I've marked them as such.

2017-10-12 19:57 UTC, nmav commented on ipcalc.c
> +static int randomize(void *ptr, ssize_t size)
Why would you allow providing a negative value as size?

2017-10-12 19:57 UTC, nmav commented on ipcalc.c
>  }
r+

2017-10-12 19:57 UTC, nmav commented on ipcalc.c
> -	memset(&mask, 0, sizeof(mask));
r+

2017-10-12 19:57 UTC, nmav commented on ipcalc-tests
>  }
r+

2017-10-12 19:57 UTC, nmav commented on ipcalc.1
> -Report bugs at https://github.com/nmav/ipcalc/issues
r+

2017-10-12 19:57 UTC, nmav commented on ipcalc.c
> -int get_ipv4_info(const char *ipStr, int prefix, ip_info_st * info,
As it is never modified, I think having the ipStr marked as const is the right thing here.

2017-10-12 19:57 UTC, nmav commented on ipcalc.c
>  	if (familyIPv6 && familyIPv4) {
r+

2017-10-12 19:57 UTC, nmav commented on netsplit.c
>  }
r+
I like this change.
A question is why do you bother with such a change for a command line tool? Are you using parts as library?

2017-10-12 19:57 UTC, nmav commented on ipcalc.c
>  }
I find flags quite easier to handle and manipulate. That is, you can mask multiple easier, and it is harder to forget unused variables around. The whole discussion is bikeshedding though, one way or another is fine. Unless you really have a good argument, I'd keep the existing way for no particular reason.

r-

2017-10-12 19:57 UTC, nmav commented on ipcalc-geoip.c
> +#include <error.h>
These are glibc functions not intended for portable programs.  They are nice, but I don't see a significant improvement to justify losing the portability.

2017-10-12 19:57 UTC, nmav commented on ipcalc.c
> -			}
r+

2017-10-12 19:57 UTC, nmav commented on netsplit.c
>  				j = 1;
r+

2017-10-12 19:57 UTC, nmav commented on ipcalc.h
>  char *calc_reverse_dns6(struct in6_addr *ip, unsigned prefix);
r+

2018-07-17 07:35 UTC, nmav commented
Moved repo to https://gitlab.com/ipcalc/ipcalc

2018-07-17 07:35 UTC, closed without merging